---
exclusions:
  type: list
  list_type: simple
  default: ""
  description:
    en: 'Relative paths added to this setting will not display the Unanswered 
        filter. For example, <b>/</b> would be used for the home page and
        <b>/top</b> for the top topics page. Be sure to adjust to your liking.'
restrict_to_groups:
  type: list
  list_type: group
  default: ""
  description:
    en: 'Only display the filter for these groups'
